# Generated by Django 5.1.3 on 2025-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_items_to_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipient_account_number',
            field=models.CharField(blank=True, help_text='رقم الحساب المستلم', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_account_number',
            field=models.CharField(blank=True, help_text='رقم الحساب الراسل', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='transferor_name',
            field=models.CharField(blank=True, help_text='اسم المحول', max_length=200),
        ),
    ]
