# Generated by Django 5.1.3 on 2025-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_payment_recipient_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cheque_account_number',
            field=models.CharField(blank=True, help_text='رقم الحساب الذي سيخضع فيه الشيك', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='تاريخ الشيك', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_holder_name',
            field=models.CharField(blank=True, help_text='اسم صاحب الشيك', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_account_number',
            field=models.CharField(blank=True, help_text='رقم الحساب الراسل (للتحويل البنكي)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transferor_name',
            field=models.CharField(blank=True, help_text='اسم المحول (للتحويل البنكي) / اسم الراسل (للإيداع النقدي)', max_length=200),
        ),
    ]
