# Generated by Django 5.1.3 on 2025-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_payment_cheque_account_number_payment_cheque_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_payment_attachments',
            field=models.FileField(blank=True, help_text='مرفقات دفعة البنك', null=True, upload_to='payments/bank_attachments/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='completion_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسبة الإنجاز', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='project_financial_account',
            field=models.CharField(blank=True, help_text='رقم الحساب المالي للمشروع (يبدأ بـ PRJ)', max_length=100),
        ),
    ]
