# Generated by Django 5.1.3 on 2025-12-07 12:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_payment_bank_payment_attachments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['-approval_date', '-created_at'], 'verbose_name': 'Price Change Order', 'verbose_name_plural': 'Price Change Orders'},
        ),
        migrations.AddField(
            model_name='variation',
            name='consultant_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أتعاب الاستشاري', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='الخصم', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ النهائي', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الصافي', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='net_amount_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الصافي بالضريبة', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الإجمالي', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_invoice_file',
            field=models.FileField(blank=True, help_text='فاتورة التعديل', null=True, upload_to='variations/invoices/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_number',
            field=models.CharField(blank=True, help_text='رقم التعديل', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='الضريبة', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ (legacy - use final_amount)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.TextField(blank=True, help_text='الوصف'),
        ),
    ]
