# Generated by Django 5.1.3 on 2025-12-07 13:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_variation_options_variation_consultant_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='consultant_fees_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة أتعاب الاستشاري (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='consultant_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أتعاب الاستشاري (محسوبة تلقائياً)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
