# Generated by Django 5.1.3 on 2025-12-07 13:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_variation_consultant_fees_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='contractor_engineer_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أتعاب مهندس المقاول (Head and Profit) (محسوبة تلقائياً)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='variation',
            name='contractor_engineer_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة مهندس المقاول (Head and Profit) (%) من المبلغ النهائي', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
