# Generated by Django 5.1.3 on 2025-12-07 13:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_variation_contractor_engineer_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='consultant_fees_percentage',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='contractor_engineer_percentage',
        ),
        migrations.AlterField(
            model_name='variation',
            name='consultant_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أتعاب الاستشاري (مبلغ ثابت)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='contractor_engineer_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مهندس المقاول (Head and Profit) (مبلغ ثابت)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الفعلي', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
