# Generated by Django 5.1.3 on 2025-12-09 08:51

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_variation_consultant_fees_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualinvoice',
            name='initial_invoice',
        ),
        migrations.AlterField(
            model_name='buildinglicense',
            name='building_license_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.BuildingLicense.get_building_license_file_path),
        ),
        migrations.AlterField(
            model_name='siteplan',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.SitePlan.get_application_file_path),
        ),
        migrations.AlterField(
            model_name='siteplanowner',
            name='id_attachment',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.SitePlanOwner.get_id_attachment_path),
        ),
        migrations.DeleteModel(
            name='InitialInvoice',
        ),
    ]
