# Generated by Django 5.1.3 on 2025-12-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_actualinvoice_initial_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved_materials_table_file',
            field=models.FileField(blank=True, help_text='جدول المواد المعتمدة', null=True, upload_to='contracts/materials/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractual_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات تعاقدية', null=True, upload_to='contracts/drawings/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='general_specifications_file',
            field=models.FileField(blank=True, help_text='المواصفات العامة والخاصة', null=True, upload_to='contracts/specifications/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price_offer_file',
            field=models.FileField(blank=True, help_text='عرض السعر', null=True, upload_to='contracts/price_offer/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quantities_table_file',
            field=models.FileField(blank=True, help_text='جدول الكميات', null=True, upload_to='contracts/quantities/'),
        ),
    ]
