# Generated by Django 5.1.3 on 2025-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_contract_approved_materials_table_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_order_notes',
            field=models.TextField(blank=True, help_text='ملاحظات أمر المباشرة'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='extensions',
            field=models.JSONField(blank=True, default=list, help_text="قائمة التمديدات: [{'reason': 'string', 'days': int, 'months': int, 'extension_date': 'string', 'approval_number': 'string', 'file_url': 'string', 'file_name': 'string'}, ...]"),
        ),
    ]
