# Generated by Django 5.1.3 on 2025-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_contract_start_order_notes_alter_contract_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplanowner',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='العمر محسوب تلقائياً من رقم الهوية', null=True),
        ),
    ]
