# Generated by Django 5.1.3 on 2025-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_age_to_siteplanowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplanowner',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='المالك المفوض (يتم اختياره صراحة)'),
        ),
    ]
