# Generated by Django 5.1.3 on 2025-12-15 05:14

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0015_add_is_authorized_to_siteplanowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='اسم الاستشاري (عربي)', max_length=200)),
                ('name_en', models.CharField(blank=True, help_text='اسم الاستشاري (إنجليزي)', max_length=200)),
                ('license_no', models.CharField(blank=True, help_text='رقم رخصة الاستشاري', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='صورة الاستشاري', null=True, upload_to=projects.models.Consultant.get_consultant_image_path)),
                ('phone', models.CharField(blank=True, help_text='رقم الهاتف', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='البريد الإلكتروني', max_length=254)),
                ('address', models.TextField(blank=True, help_text='العنوان')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات')),
                ('tenant', models.ForeignKey(blank=True, help_text='الشركة التي ينتمي إليها هذا السجل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='authentication.tenant')),
            ],
            options={
                'verbose_name': 'استشاري',
                'verbose_name_plural': 'استشاريون',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='design_consultant',
            field=models.ForeignKey(blank=True, help_text='استشاري التصميم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_licenses', to='projects.consultant'),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='supervision_consultant',
            field=models.ForeignKey(blank=True, help_text='استشاري الإشراف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_licenses', to='projects.consultant'),
        ),
        migrations.CreateModel(
            name='ProjectConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('design', 'استشاري التصميم'), ('supervision', 'استشاري الإشراف')], help_text='دور الاستشاري في المشروع', max_length=20)),
                ('consultant', models.ForeignKey(help_text='الاستشاري', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.consultant')),
                ('project', models.ForeignKey(help_text='المشروع', on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='projects.project')),
                ('tenant', models.ForeignKey(blank=True, help_text='الشركة التي ينتمي إليها هذا السجل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='authentication.tenant')),
            ],
            options={
                'verbose_name': 'استشاري المشروع',
                'verbose_name_plural': 'استشاريو المشاريع',
                'ordering': ['project', 'role'],
            },
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['tenant', 'name'], name='projects_co_tenant__190ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['tenant', 'license_no'], name='projects_co_tenant__ed191f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultant',
            unique_together={('tenant', 'name', 'license_no')},
        ),
        migrations.AddIndex(
            model_name='projectconsultant',
            index=models.Index(fields=['project', 'role'], name='projects_pr_project_a0d66f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectconsultant',
            index=models.Index(fields=['consultant', 'role'], name='projects_pr_consult_375115_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectconsultant',
            unique_together={('project', 'consultant', 'role')},
        ),
    ]
