# Generated by Django 5.1.3 on 2025-12-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_consultant_buildinglicense_design_consultant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultant',
            unique_together=set(),
        ),
    ]
