# Generated by Django 5.1.3 on 2025-12-24 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_consultant_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_approval_notes',
            field=models.TextField(blank=True, help_text='ملاحظات الاعتماد النهائي'),
        ),
        migrations.AddField(
            model_name='project',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ الاعتماد النهائي', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي أعتمد المشروع نهائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final_approved', 'Final Approved'), ('delete_requested', 'Delete Requested'), ('delete_approved', 'Delete Approved')], default='draft', help_text='حالة الموافقة على المشروع', max_length=30),
        ),
    ]
