# Generated by Django 4.2.7 on 2025-12-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0018_project_final_approval_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_order_date', models.DateField(blank=True, null=True)),
                ('start_order_notes', models.TextField(blank=True, help_text='ملاحظات أمر المباشرة')),
                ('start_order_file', models.FileField(blank=True, null=True, upload_to='start_orders/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_order', to='projects.project')),
                ('tenant', models.ForeignKey(blank=True, help_text='الشركة التي ينتمي إليها هذا السجل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='authentication.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
