# Generated by Django 4.2.7 on 2025-12-25 09:31

from django.db import migrations, models


def migrate_start_order_data(apps, schema_editor):
    """نقل بيانات أمر المباشرة من Contract إلى StartOrder"""
    Contract = apps.get_model('projects', 'Contract')
    StartOrder = apps.get_model('projects', 'StartOrder')
    
    # نقل البيانات من Contract إلى StartOrder
    for contract in Contract.objects.filter(
        models.Q(start_order_date__isnull=False) | 
        models.Q(start_order_file__isnull=False) |
        models.Q(start_order_notes__isnull=False)
    ).exclude(start_order_notes=''):
        # التحقق من عدم وجود StartOrder للمشروع بالفعل
        if not StartOrder.objects.filter(project_id=contract.project_id).exists():
            StartOrder.objects.create(
                project_id=contract.project_id,
                tenant_id=contract.tenant_id if hasattr(contract, 'tenant_id') else None,
                start_order_date=contract.start_order_date,
                start_order_notes=contract.start_order_notes,
                start_order_file=contract.start_order_file,
            )


def reverse_migrate_start_order_data(apps, schema_editor):
    """إرجاع البيانات من StartOrder إلى Contract (للتراجع)"""
    Contract = apps.get_model('projects', 'Contract')
    StartOrder = apps.get_model('projects', 'StartOrder')
    
    for start_order in StartOrder.objects.all():
        try:
            contract = Contract.objects.get(project_id=start_order.project_id)
            contract.start_order_date = start_order.start_order_date
            contract.start_order_notes = start_order.start_order_notes
            contract.start_order_file = start_order.start_order_file
            contract.save(update_fields=['start_order_date', 'start_order_notes', 'start_order_file'])
        except Contract.DoesNotExist:
            pass  # إذا لم يوجد عقد، نتخطى


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_create_start_order_model'),
    ]

    operations = [
        migrations.RunPython(migrate_start_order_data, reverse_migrate_start_order_data),
    ]
