# Generated by Django 4.2.7 on 2025-12-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_migrate_start_order_data_from_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='start_order_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_order_file',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_order_notes',
        ),
    ]
