# Generated by Django 4.2.7 on 2025-12-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_start_order_from_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='architectural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات المعمارية', null=True, upload_to='contracts/drawings/architectural/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='decoration_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الديكور', null=True, upload_to='contracts/drawings/decoration/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='mep_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات MEP', null=True, upload_to='contracts/drawings/mep/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='structural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات الإنشائية', null=True, upload_to='contracts/drawings/structural/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractual_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات تعاقدية (قديم - سيتم إزالته)', null=True, upload_to='contracts/drawings/'),
        ),
    ]
