# Generated by Django 4.2.7 on 2025-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_split_contractual_drawings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'مشاريع'},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'internal_code'], name='projects_pr_tenant__0a617d_idx'),
        ),
    ]
