# Generated by Django 4.2.7 on 2025-12-25 14:18
# Modified to add fields first, then migrate data in next migration, then remove from Contract

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_add_project_meta_index'),
    ]

    operations = [
        # ✅ إضافة الحقول إلى StartOrder أولاً (قبل إزالة extensions من Contract)
        migrations.AddField(
            model_name='startorder',
            name='extensions',
            field=models.JSONField(blank=True, default=list, help_text="قائمة التمديدات: [{'reason': 'string', 'days': int, 'months': int, 'extension_date': 'string', 'approval_number': 'string', 'file_url': 'string', 'file_name': 'string'}, ...]"),
        ),
        migrations.AddField(
            model_name='startorder',
            name='project_end_date',
            field=models.DateField(blank=True, help_text='تاريخ نهاية المشروع محسوب بناءً على start_order_date + project_duration_months + extensions', null=True),
        ),
        # ✅ لا نزيل extensions من Contract هنا - سيتم ذلك في migration لاحق بعد نقل البيانات
    ]
