# Generated by Django 4.2.7 on 2025-12-25 17:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_extensions_from_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ (legacy - use final_amount)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='consultant_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أتعاب الاستشاري (محسوبة تلقائياً من النسبة)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='consultant_fees_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة أتعاب الاستشاري (%) من المبلغ الفعلي', max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='contractor_engineer_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مهندس المقاول (Head and Profit) (مبلغ ثابت)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='الخصم', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الفعلي', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الصافي', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='net_amount_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الصافي بالضريبة', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='المبلغ الإجمالي', max_digits=14),
        ),
        migrations.AlterField(
            model_name='variation',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='الضريبة', max_digits=14),
        ),
    ]
