# Generated by Django 4.2.7 on 2025-12-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_min_value_validator_from_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='total_floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='المساحة الطابقية للمشروع بالمتر المربع', max_digits=12, null=True),
        ),
    ]
