# Generated by Django 5.1.3 on 2025-12-28 08:27

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_add_total_floor_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarding',
            name='awarding_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.Awarding.get_awarding_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='approved_materials_table_file',
            field=models.FileField(blank=True, help_text='جدول المواد المعتمدة', null=True, upload_to=projects.models.Contract.get_approved_materials_table_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='architectural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات المعمارية', max_length=500, null=True, upload_to=projects.models.Contract.get_architectural_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_appendix_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.Contract.get_contract_appendix_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_explanation_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.Contract.get_contract_explanation_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.Contract.get_contract_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractual_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات تعاقدية (قديم - سيتم إزالته)', null=True, upload_to=projects.models.Contract.get_contractual_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='decoration_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الديكور', max_length=500, null=True, upload_to=projects.models.Contract.get_decoration_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='general_specifications_file',
            field=models.FileField(blank=True, help_text='المواصفات العامة والخاصة', null=True, upload_to=projects.models.Contract.get_general_specifications_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mep_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات MEP', max_length=500, null=True, upload_to=projects.models.Contract.get_mep_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_offer_file',
            field=models.FileField(blank=True, help_text='عرض السعر', null=True, upload_to=projects.models.Contract.get_price_offer_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quantities_table_file',
            field=models.FileField(blank=True, help_text='جدول الكميات', null=True, upload_to=projects.models.Contract.get_quantities_table_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='structural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات الإنشائية', max_length=500, null=True, upload_to=projects.models.Contract.get_structural_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_payment_attachments',
            field=models.FileField(blank=True, help_text='مرفقات دفعة البنك', null=True, upload_to=projects.models.Payment.get_bank_payment_attachments_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit_slip',
            field=models.FileField(blank=True, help_text='Deposit Slip / Bank Deposit Proof', null=True, upload_to=projects.models.Payment.get_deposit_slip_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='Invoice Used for Payment (فاتورة الدفع)', null=True, upload_to=projects.models.Payment.get_payment_invoice_file_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_voucher',
            field=models.FileField(blank=True, help_text='Receipt Voucher (سند قبض)', null=True, upload_to=projects.models.Payment.get_receipt_voucher_path),
        ),
        migrations.AlterField(
            model_name='startorder',
            name='start_order_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.StartOrder.get_start_order_file_path),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_invoice_file',
            field=models.FileField(blank=True, help_text='فاتورة التعديل', null=True, upload_to=projects.models.Variation.get_variation_invoice_file_path),
        ),
    ]
