# Generated by Django 5.1.3 on 2025-12-28 09:01

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_awarding_awarding_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='approved_materials_table_file',
            field=models.FileField(blank=True, help_text='جدول المواد المعتمدة', max_length=500, null=True, upload_to=projects.models.Contract.get_approved_materials_table_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_appendix_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.Contract.get_contract_appendix_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_explanation_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.Contract.get_contract_explanation_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.Contract.get_contract_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractual_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات تعاقدية (قديم - سيتم إزالته)', max_length=500, null=True, upload_to=projects.models.Contract.get_contractual_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='general_specifications_file',
            field=models.FileField(blank=True, help_text='المواصفات العامة والخاصة', max_length=500, null=True, upload_to=projects.models.Contract.get_general_specifications_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_offer_file',
            field=models.FileField(blank=True, help_text='عرض السعر', max_length=500, null=True, upload_to=projects.models.Contract.get_price_offer_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quantities_table_file',
            field=models.FileField(blank=True, help_text='جدول الكميات', max_length=500, null=True, upload_to=projects.models.Contract.get_quantities_table_file_path),
        ),
    ]
