# Generated by Django 5.1.3 on 2025-12-28 12:00

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_contract_approved_materials_table_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ac_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات التكييف', max_length=500, null=True, upload_to=projects.models.Contract.get_ac_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='electrical_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الكهرباء', max_length=500, null=True, upload_to=projects.models.Contract.get_electrical_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='water_supply_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات إمداد المياه', max_length=500, null=True, upload_to=projects.models.Contract.get_water_supply_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='drainage_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الصرف الصحي', max_length=500, null=True, upload_to=projects.models.Contract.get_drainage_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='telecommunication_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الاتصالات', max_length=500, null=True, upload_to=projects.models.Contract.get_telecommunication_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='fire_fighting_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات مكافحة الحرائق', max_length=500, null=True, upload_to=projects.models.Contract.get_fire_fighting_drawings_file_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='cctv_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات كاميرات المراقبة', max_length=500, null=True, upload_to=projects.models.Contract.get_cctv_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='architectural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات المعمارية', max_length=500, null=True, upload_to=projects.models.Contract.get_architectural_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='structural_drawings_file',
            field=models.FileField(blank=True, help_text='المخططات الإنشائية', max_length=500, null=True, upload_to=projects.models.Contract.get_structural_drawings_file_path),
        ),
    ]

