# Generated by Django 4.2.7 on 2025-12-29 11:44

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_add_new_contract_drawings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinglicense',
            name='building_license_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.BuildingLicense.get_building_license_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractual_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات تعاقدية (قديم)', max_length=500, null=True, upload_to=projects.models.Contract.get_contractual_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='decoration_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات الديكور (قديم)', max_length=500, null=True, upload_to=projects.models.Contract.get_decoration_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mep_drawings_file',
            field=models.FileField(blank=True, help_text='مخططات MEP (قديم)', max_length=500, null=True, upload_to=projects.models.Contract.get_mep_drawings_file_path),
        ),
        migrations.AlterField(
            model_name='siteplanowner',
            name='id_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.SitePlanOwner.get_id_attachment_path),
        ),
    ]
