# Generated by Django 4.2.7 on 2025-12-29 13:14

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_add_max_length_to_building_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startorder',
            name='start_order_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.StartOrder.get_start_order_file_path),
        ),
    ]
