# Generated by Django 4.2.7 on 2025-12-29 14:05

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0033_add_max_length_to_start_order_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_start_date', models.DateField(blank=True, help_text='تاريخ بداية المشروع', null=True)),
                ('project_end_date', models.DateField(blank=True, help_text='تاريخ نهاية المشروع (محسوب تلقائياً)', null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_schedule', to='projects.project')),
                ('tenant', models.ForeignKey(blank=True, help_text='الشركة التي ينتمي إليها هذا السجل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='authentication.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcavationStartNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_date', models.DateField(blank=True, help_text='تاريخ إشعار بدء الحفر', null=True)),
                ('notice_file', models.FileField(blank=True, max_length=500, null=True, upload_to=projects.models.ExcavationStartNotice.get_excavation_notice_file_path)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excavation_start_notice', to='projects.project')),
                ('tenant', models.ForeignKey(blank=True, help_text='الشركة التي ينتمي إليها هذا السجل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='authentication.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
