# Generated by Django 4.2.7 on 2025-12-29 14:41

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_project_schedule_and_excavation_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschedule',
            name='schedule_file',
            field=models.FileField(blank=True, help_text='ملف الجدول الزمني للمشروع', max_length=500, null=True, upload_to=projects.models.ProjectSchedule.get_project_schedule_file_path),
        ),
    ]
